### ISSUE TITLE
Getting error when trying to import numpy 1.23.5 with mkl_fft >1.3.8 in Python 3.8 environment

### ISSUE THREAD

**Issue by DManowitz** [IntelPython/mkl_fft#105]
I have installed numpy 1.23.5 in a Python 3.8 environment on Windows.  If I have mkl_fft >1.3.8 installed, I get the following exception when I try to import numpy:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\...\lib\site-packages\numpy\__init__.py", line 165, in <module>
    from . import fft
  File "C:\...\lib\site-packages\numpy\fft\__init__.py", line 216, in <module>
    import mkl_fft._numpy_fft as _nfft
  File "C:\...\lib\site-packages\mkl_fft\__init__.py", line 27, in <module>
    from ._pydfti import (fft, ifft, fft2, ifft2, fftn, ifftn, rfft, irfft,
  File "mkl_fft\\_pydfti.pyx", line 32, in init mkl_fft._pydfti
AttributeError: partially initialized module 'numpy' has no attribute '__version__' (most likely due to a circular import)
```

However, with mkl_fft 1.3.8 installed, I get no error.

**Comment by vtavana** [comment]
Closing this issue as this was inactive for a long time.

The most recent version `mkl-fft-1.3.14` is available for python 3.9, 3.10, 3.11, 312 and works with numpy>=1.26.4. If you have any problems with the newest version please open a new issue.
